allowBuilds:
  bufferutil: true
  electron: true
  electron-winstaller: true
  esbuild: true
  node-pipewire: true
  register-scheme@https://codeload.github.com/devsnek/node-register-scheme/tar.gz/e7cc9a63a1f512565da44cb57316d9fb10750e17: true
  utf-8-validate: true

nodeLinker: hoisted

blockExoticSubdeps: false # required to make discord-rpc work

# Override for node 26 bug
overrides:
  yauzl: ^3.3.1
